//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borys.Nachrichten.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Borys.Nachrichten.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;tr&gt;
        ///&lt;h2&gt;$nummer$: $titel$&lt;/h2&gt;
        ///&lt;p&gt;$quelle$ am $datum$. $category$&lt;/p&gt;
        ///&lt;p&gt;$meldung$&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;$link$&quot;&gt;mehr dazu hier ... &lt;/a&gt;&lt;/p&gt;
        ///&lt;/tr&gt; ähnelt.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die css ähnelt.
        /// </summary>
        internal static string cssDir {
            get {
                return ResourceManager.GetString("cssDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /* farben2.css CSS - Cascading Style Sheet */
        ////* Palette color codes */
        ////* Palette URL: http://paletton.com/#uid=53+1a0kllll01QlaGuev+cs+W3z 
        ///*/
        ///:root
        ///	{
        ///		--p3:	#0A0A45 ;
        ///		--p4:	#000014 ;
        ///		--s20: 	#2D8632;
        ///		--s22:	#7EBE82 ;
        ///		--s11b:	#eed8ee;
        ///		--s12:	#BF80A5 ;
        ///		--s13: 	#4F002E ;		
        ///	}	
        /// ähnelt.
        /// </summary>
        internal static string farben {
            get {
                return ResourceManager.GetString("farben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die farben.css ähnelt.
        /// </summary>
        internal static string farbenDatei {
            get {
                return ResourceManager.GetString("farbenDatei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;/tbody&gt;&lt;tfoot &gt;
        ///    &lt;tr&gt;
        ///      &lt;td &gt;
        ///&lt;strong&gt; &lt;/strong&gt;
        ///	  &lt;/td&gt;
        ///      &lt;td&gt;
        ///&lt;strong&gt; &lt;/strong&gt;
        ///	  &lt;/td&gt;
        ///      &lt;td&gt;
        ///
        ///	  &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///  &lt;/tfoot&gt;
        ///&lt;/table&gt;
        ///&lt;div&gt;
        ///&lt;footer&gt;&lt;ul&gt;&lt;li&gt;$nummer$ Meldungen ausgegeben.&lt;/li&gt;
        ///&lt;li&gt;
        ///$footer$
        ///&lt;/li&gt;&lt;/ul&gt;&lt;/footer&gt;&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        /// ähnelt.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;head&gt;
        ///&lt;html lang=&quot;de&quot;&gt;
        ///  &lt;link href=&quot;/css/farben.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;link href=&quot;/css/stil.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///  &lt;style&gt;
        ///  .gc {
        ///	  display: grid;
        ///	  grid-template-columns: auto auto auto auto;
        ///  }
        /// .d	{
        ///	 border-color: var(--s13);
        ///	 border-width: 2px;
        ///	 border-style: 	 solid;
        ///	}
        /// .c	{
        ///	 text-align: center;
        ///	 font-weight:bold;
        ///	}
        ///  &lt;/style&gt;
        ///  &lt;title&gt;News&lt;/title&gt;
        ///&lt;/head&gt;&lt;body 
        ///  background-color=&quot;lightblue;&quot;&gt;
        ///&lt;h1&gt;Nachrichte [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die html
        ///{
        ///    font-family: Verdana, Helvetica, Sans-Serif;
        ///    margin: 0.2em ;
        ///}
        ///body
        ///{
        ///	background: white;
        ///}
        ///	/* Ränder `oben rechts unten links */
        ///	/* Header gibts von 1 bis 6 */
        ///h1,h2,h3,h4,h5,h6 
        ///{
        ///	letter-spacing: +.05em;
        ///	background:		var(--s22);
        ///    color: 			var(--p4);	/*color-primary-4*/
        ///    padding: 		0.2em 1em 0.1em 1em;
        ///    font-weight: 	bold;
        ///	border-color: var(--s20);
        ///	border-width: 3mm;
        ///	border-style: 	none none none solid;
        ///}
        ///
        ///.btn {
        ///  border: none; 		/* Remove borders */
        ///  border-radius: 12px;  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string stil {
            get {
                return ResourceManager.GetString("stil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stil.css ähnelt.
        /// </summary>
        internal static string stilDatei {
            get {
                return ResourceManager.GetString("stilDatei", resourceCulture);
            }
        }
    }
}
