//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQLHilfe.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySQLHilfe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `meldungen` (
        /// `hash` bigint(20) NOT NULL,
        /// `datum` timestamp NOT NULL DEFAULT current_timestamp(),
        /// `category` tinytext DEFAULT NULL,
        /// `quelle` tinytext DEFAULT NULL,
        /// `titel` text DEFAULT NULL,
        /// `meldung` text DEFAULT NULL,
        /// `link` tinytext DEFAULT NULL,
        /// `w1` tinyint(1) NOT NULL DEFAULT 0 COMMENT &apos;Einzelwörter erfasst&apos;,
        /// `w2` tinyint(1) NOT NULL DEFAULT 0 COMMENT &apos;2-Wörter erfasst&apos;,
        /// `w3` tinyint(1) NOT NULL DEFAULT 0 COMMENT &apos;3-Wörter erfasst&apos;,
        /// `w4` tinyint(1) NOT NULL DEFAULT 0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreateMld {
            get {
                return ResourceManager.GetString("CreateMld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `tasks` (
        /// `id` int(11) NOT NULL AUTO_INCREMENT,
        /// `programm` tinytext DEFAULT NULL,
        /// `aufgabe` tinyint(4) NOT NULL DEFAULT 0,
        /// PRIMARY KEY (`id`)
        ///) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT=&apos;nächster notwendiger Programmschritt&apos; ähnelt.
        /// </summary>
        internal static string CreateTsk {
            get {
                return ResourceManager.GetString("CreateTsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `wichtige` (
        /// `id` int(11) NOT NULL AUTO_INCREMENT,
        /// `wort` tinytext DEFAULT NULL,
        /// `faktor` double DEFAULT NULL,
        /// PRIMARY KEY (`id`)
        ///) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT=&apos;wichtige Wortfolgen in den neuesten Meldungen&apos; ähnelt.
        /// </summary>
        internal static string CreateWichtige {
            get {
                return ResourceManager.GetString("CreateWichtige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `woerter1` (
        /// `wort` tinytext DEFAULT NULL COMMENT &apos;Wort/Wortfolge&apos;,
        /// `hash` int(11) NOT NULL COMMENT &apos;Hash über Wortfolge&apos;,
        /// `anzahl` int(11) unsigned DEFAULT 0 COMMENT &apos;absolute Anzahl&apos;,
        /// `gesamt` int(10) unsigned DEFAULT NULL COMMENT &apos;Gesamtzahl, auf die sich rel. H. bezieht&apos;,
        /// `rang` int(11) unsigned DEFAULT NULL COMMENT &apos;Rang nach Anzahl&apos;,
        /// `relh` double unsigned DEFAULT NULL COMMENT &apos;relative Häufigkeit&apos;,
        /// `entr` float unsigned DEFAULT NULL COMMENT &apos;Wort-Entropie&apos;,
        /// `beitrag` doub [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreateWörter {
            get {
                return ResourceManager.GetString("CreateWörter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `woerterneu1` (
        /// `wort` tinytext DEFAULT NULL COMMENT &apos;Wort/Wortfolge&apos;,
        /// `hash` int(11) NOT NULL COMMENT &apos;Hash über Wortfolge&apos;,
        /// `anzahl` int(11) unsigned DEFAULT 0 COMMENT &apos;absolute Anzahl&apos;,
        /// `gesamt` int(10) unsigned DEFAULT NULL COMMENT &apos;Gesamtzahl, auf die sich rel. H. bezieht&apos;,
        /// `rang` int(11) unsigned DEFAULT NULL COMMENT &apos;Rang nach Anzahl&apos;,
        /// `relh` double unsigned DEFAULT NULL COMMENT &apos;relative Häufigkeit&apos;,
        /// `entr` float unsigned DEFAULT NULL COMMENT &apos;Wort-Entropie&apos;,
        /// `beitrag` d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CreateWörterneu {
            get {
                return ResourceManager.GetString("CreateWörterneu", resourceCulture);
            }
        }
    }
}
