//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borys.Nachrichten.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die
    // .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
       // internal Resources() {        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Borys.Nachrichten.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;tr&gt;
        ///&lt;h2&gt;$titel$&lt;/h2&gt;
        ///&lt;p&gt;$quelle$ am $datum$&lt;/p&gt;
        ///&lt;p&gt;$category$&lt;/p&gt;
        ///&lt;p&gt;$meldung$&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;$link$&quot;&gt;mehr: &lt;/a&gt;&lt;/p&gt;
        ///&lt;/tr&gt; ähnelt.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;/tbody&gt;&lt;tfoot &gt;
        ///    &lt;tr&gt;
        ///      &lt;td &gt;
        ///&lt;strong&gt; &lt;/strong&gt;
        ///	  &lt;/td&gt;
        ///      &lt;td&gt;
        ///&lt;strong&gt; &lt;/strong&gt;
        ///	  &lt;/td&gt;
        ///      &lt;td&gt;
        ///
        ///	  &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///  &lt;/tfoot&gt;
        ///&lt;/table&gt;
        ///&lt;div&gt;
        ///&lt;footer&gt;&lt;ul&gt;&lt;li&gt;
        ///$footer$
        ///&lt;/li&gt;&lt;/ul&gt;&lt;/footer&gt;&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        /// ähnelt.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;head&gt;
        ///&lt;html lang=&quot;de&quot;&gt;
        ///  &lt;link href=&quot;/css/farben.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;link href=&quot;/css/stil.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///  &lt;style&gt;
        ///  .gc {
        ///	  display: grid;
        ///	  grid-template-columns: auto auto auto auto;
        ///  }
        /// .d	{
        ///	 border-color: var(--s13);
        ///	 border-width: 2px;
        ///	 border-style: 	 solid;
        ///	}
        /// .c	{
        ///	 text-align: center;
        ///	 font-weight:bold;
        ///	}
        ///  &lt;/style&gt;
        ///  &lt;title&gt;News&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;p&gt;erstellt mit $name$, V$version$&lt;/p&gt; ähnelt.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
    }
}
